# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Notes
description: A programming blog
  
baseurl: "/journal"
url: "http://ashlynnpai.github.io"
github_username: ashlynnpai
codepen_username: ashlynnpai
google_verify: 4gvGlZHCAFLuLpfAtoHc_uK7DWE3nGElObAOsQcLO5I

disqus:
    shortname: ashlynn

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jemoji
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]
plugins_dir:
  - jekyll-sitemap

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
paginate: nil
paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 1
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

